FROM maven:3.9.6-eclipse-temurin-17 AS build
WORKDIR /workspace
COPY pom.xml ./
COPY src ./src
RUN mvn -B -DskipTests package

FROM eclipse-temurin:17-jdk-jammy
WORKDIR /app
COPY --from=build /workspace/target/service-java-0.0.1-SNAPSHOT.jar ./service-java.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","/app/service-java.jar"]
