#!/bin/bash

# KN_04 Keycloak OIDC Demo - Quick Start Guide
# This script provides step-by-step instructions for setting up the demo

echo "================================================"
echo "KN_04: IAM with Keycloak - Setup Guide"
echo "================================================"
echo ""

echo "Step 1: Starting services with Docker Compose..."
echo "Run: docker compose up --build"
echo ""
echo "Wait for Keycloak to fully start (about 60 seconds)..."
echo "You should see: 'Keycloak ... started'"
echo ""
echo "Press Enter when services are running..."
read

echo "================================================"
echo "Step 2: Configure Keycloak"
echo "================================================"
echo ""
echo "1. Open Keycloak Admin Console:"
echo "   URL: http://localhost:8081"
echo "   Username: admin"
echo "   Password: admin"
echo ""
echo "2. Create a Realm:"
echo "   - Click dropdown in top-left (says 'master')"
echo "   - Click 'Create Realm'"
echo "   - Realm name: demo-realm"
echo "   - Click 'Create'"
echo ""
echo "3. Create a Client:"
echo "   - Go to 'Clients' in left menu"
echo "   - Click 'Create client'"
echo "   - Client ID: demo-client"
echo "   - Client Type: OpenID Connect"
echo "   - Click 'Next'"
echo "   - Client authentication: ON"
echo "   - Authentication flow: Standard flow + Direct access grants"
echo "   - Click 'Next'"
echo "   - Valid redirect URIs: http://localhost:8080/*"
echo "   - Valid post logout redirect URIs: http://localhost:8080/*"
echo "   - Web origins: http://localhost:8080"
echo "   - Click 'Save'"
echo ""
echo "4. Get Client Secret:"
echo "   - In client settings, go to 'Credentials' tab"
echo "   - Copy the 'Client secret'"
echo "   - Update src/main/resources/application.properties"
echo "   - Replace 'your-client-secret' with the actual secret"
echo ""
echo "5. Create a User:"
echo "   - Go to 'Users' in left menu"
echo "   - Click 'Add user'"
echo "   - Username: testuser"
echo "   - Email: testuser@example.com"
echo "   - First name: Test"
echo "   - Last name: User"
echo "   - Email verified: ON"
echo "   - Click 'Create'"
echo "   - Go to 'Credentials' tab"
echo "   - Click 'Set password'"
echo "   - Password: password"
echo "   - Temporary: OFF"
echo "   - Click 'Save'"
echo ""
echo "Press Enter after completing Keycloak configuration..."
read

echo "================================================"
echo "Step 3: Update Application Configuration"
echo "================================================"
echo ""
echo "Edit: src/main/resources/application.properties"
echo "Update the client secret with the one you copied from Keycloak"
echo ""
echo "Press Enter after updating application.properties..."
read

echo "================================================"
echo "Step 4: Restart Application"
echo "================================================"
echo ""
echo "Run: docker compose restart app"
echo "Or: docker compose up --build app"
echo ""
echo "Press Enter after restarting the application..."
read

echo "================================================"
echo "Step 5: Test the Application"
echo "================================================"
echo ""
echo "1. Open: http://localhost:8080"
echo "   - You should see the home page"
echo ""
echo "2. Test Public Page: http://localhost:8080/public"
echo "   - Accessible without login"
echo ""
echo "3. Click 'Login' button"
echo "   - You'll be redirected to Keycloak"
echo "   - Login with: testuser / password"
echo ""
echo "4. After login, access: http://localhost:8080/protected"
echo "   - You should see your user information"
echo "   - Username, email, and ID token claims"
echo ""
echo "================================================"
echo "Setup Complete!"
echo "================================================"
echo ""
echo "Useful Commands:"
echo "  - View logs: docker compose logs -f"
echo "  - Stop services: docker compose down"
echo "  - Restart app: docker compose restart app"
echo ""
echo "Troubleshooting:"
echo "  - If login fails, verify client secret in application.properties"
echo "  - Check Keycloak logs: docker compose logs keycloak"
echo "  - Check App logs: docker compose logs app"
echo ""
